In [1]:
import pandas as pd
import numpy as np

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')
test_id=test.Id
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
def clean(df):

    columns = ['Street', 'Alley', 'LandContour', 'Utilities', 'LandSlope', 'Condition1',
               'Condition2', 'RoofMatl', 'BsmtCond', 'BsmtFinType2', 'BsmtFinSF2', 'Heating',
               'CentralAir', 'Electrical', 'LowQualFinSF', 'KitchenQual', 'GarageQual',
               'PavedDrive', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 
               'MiscFeature']
    df = df.drop(columns=columns, errors='ignore')
    
    return df
train = clean(train)
test = clean(test)

In [4]:
def sp(df):
    target='SalePrice'
    df=df.dropna(subset=[target])
    return df
train=sp(train)

In [5]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LotConfig,Neighborhood,BldgType,HouseStyle,...,GarageCond,WoodDeckSF,OpenPorchSF,EnclosedPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Reg,Inside,CollgCr,1Fam,2Story,...,TA,0,61,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Reg,FR2,Veenker,1Fam,1Story,...,TA,298,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,IR1,Inside,CollgCr,1Fam,2Story,...,TA,0,42,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,IR1,Corner,Crawfor,1Fam,2Story,...,TA,0,35,272,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,IR1,FR2,NoRidge,1Fam,2Story,...,TA,192,84,0,0,12,2008,WD,Normal,250000

In [6]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LotConfig,Neighborhood,BldgType,HouseStyle,...,GarageArea,GarageCond,WoodDeckSF,OpenPorchSF,EnclosedPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Reg,Inside,NAmes,1Fam,1Story,...,730.0,TA,140,0,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,IR1,Corner,NAmes,1Fam,1Story,...,312.0,TA,393,36,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,IR1,Inside,Gilbert,1Fam,2Story,...,482.0,TA,212,34,0,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,IR1,Inside,Gilbert,1Fam,2Story,...,470.0,TA,360,36,0,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,IR1,Inside,StoneBr,TwnhsE,1Story,...,506.0,TA,0,82,0,0,1,2010,WD,Normal

In [7]:
def na_fill(df):
    for column in df.columns:
        df[column].fillna(df[column].mode()[0], inplace=True)  # Use mode()[0] to get the most frequent value
    return df

train=na_fill(train)
test=na_fill(test)

In [8]:
from sklearn import preprocessing

In [9]:
def s_n(df):
    encoders = {}
    
    # For training DataFrame
    for column in df.select_dtypes(include=['object']).columns:
        encoder = preprocessing.LabelEncoder()
        # Fill NaN values with a placeholder before fitting
        df[column] = df[column].astype(str).fillna('missing')
        df[column] = encoder.fit_transform(df[column])
        encoders[column] = encoder  # Store the encoder for each column 
    return df

In [10]:
train= s_n(train)

In [11]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LotConfig,Neighborhood,BldgType,HouseStyle,...,GarageCond,WoodDeckSF,OpenPorchSF,EnclosedPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,3,4,5,0,5,...,4,0,61,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,3,2,24,0,2,...,4,298,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,0,4,5,0,5,...,4,0,42,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,0,0,6,0,5,...,4,0,35,272,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,0,2,15,0,5,...,4,192,84,0,0,12,2008,8,4,250000

In [12]:
test=s_n(test)

In [13]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LotConfig,Neighborhood,BldgType,HouseStyle,...,GarageArea,GarageCond,WoodDeckSF,OpenPorchSF,EnclosedPorch,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,3,4,12,0,2,...,730.0,4,140,0,0,0,6,2010,8,4
1,1462,20,3,81.0,14267,0,0,12,0,2,...,312.0,4,393,36,0,12500,6,2010,8,4
2,1463,60,3,74.0,13830,0,4,8,0,4,...,482.0,4,212,34,0,0,3,2010,8,4
3,1464,60,3,78.0,9978,0,4,8,0,4,...,470.0,4,360,36,0,0,6,2010,8,4
4,1465,120,3,43.0,5005,0,4,22,4,2,...,506.0,4,0,82,0,0,1,2010,8,4

In [14]:
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
cor_matrix=train.corr()
#corr() is for finding the correlation of the matrix
Y_X_corr=cor_matrix['SalePrice'].sort_values(ascending=False)
print(Y_X_corr)
#import matplotlib.pyplot as plt
#Y_X_corr.plot(kind='bar')
#plt.title('Correlation with SalePrice')
#plt.xlabel('Features')
#plt.ylabel('Correlation Coefficient')
#plt.xticks(rotation=45)
#plt.axhline(0, color='grey', lw=0.8, ls='--')
#plt.show()

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
MasVnrArea       0.472614
Fireplaces       0.466929
GarageYrBlt      0.397778
BsmtFinSF1       0.386420
Foundation       0.382479
LotFrontage      0.329220
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
RoofStyle        0.222405
BsmtUnfSF        0.214479
SaleCondition    0.213092
Neighborhood     0.210851
HouseStyle       0.180163
BedroomAbvGr     0.168213
GarageCond       0.134740
ExterCond        0.117303
Functional       0.115328
Exterior2nd      0.103766
Exterior1st      0.103551
FireplaceQu      0.071177
MoSold           0.046432
MasVnrType       0.018216
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
YrSold          -0.028923
SaleType        -0.054911
LotConfig       -0.067396
OverallCond     -0.077856
MSSubClass      -0.084284
BldgType        -0.085591
BsmtFinType1    -0.092106
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
MSZoning        -0.166872
LotShape        -0.255580
BsmtExposure    -0.295407
GarageType      -0.302105
HeatingQC       -0.400178
GarageFinish    -0.537242
BsmtQual        -0.618025
ExterQual       -0.636884
Name: SalePrice, dtype: float64

In [16]:
threshold=0
features = Y_X_corr[abs(Y_X_corr) > threshold].index.tolist()
features.remove('SalePrice')
print(features)

['OverallQual', 'GrLivArea', 'GarageCars', 'GarageArea', 'TotalBsmtSF', '1stFlrSF', 'FullBath', 'TotRmsAbvGrd', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'Fireplaces', 'GarageYrBlt', 'BsmtFinSF1', 'Foundation', 'LotFrontage', 'WoodDeckSF', '2ndFlrSF', 'OpenPorchSF', 'HalfBath', 'LotArea', 'BsmtFullBath', 'RoofStyle', 'BsmtUnfSF', 'SaleCondition', 'Neighborhood', 'HouseStyle', 'BedroomAbvGr', 'GarageCond', 'ExterCond', 'Functional', 'Exterior2nd', 'Exterior1st', 'FireplaceQu', 'MoSold', 'MasVnrType', 'BsmtHalfBath', 'MiscVal', 'Id', 'YrSold', 'SaleType', 'LotConfig', 'OverallCond', 'MSSubClass', 'BldgType', 'BsmtFinType1', 'EnclosedPorch', 'KitchenAbvGr', 'MSZoning', 'LotShape', 'BsmtExposure', 'GarageType', 'HeatingQC', 'GarageFinish', 'BsmtQual', 'ExterQual']

In [17]:
X=train[features]
Y=train['SalePrice']
X_test=test[features]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

In [19]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error


# Initialize the GradientBoostingRegressor
gbr = GradientBoostingRegressor(random_state=42, n_estimators=100, learning_rate=0.1, max_depth=3)

# Train the model
gbr.fit(X_train, Y_train)

# Make predictions
Y_pred = gbr.predict(X_val)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(Y_val, Y_pred)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)

print("Root Mean Squared Error with GradientBoostingRegressor:", rmse)

Root Mean Squared Error with GradientBoostingRegressor: 28037.03704918174

In [27]:
# Make predictions on the filtered test set
submission = gbr.predict(X_test)

# Create a DataFrame for submission
submission_df = pd.DataFrame({
    'id': test_id.values,
    'SalePrice': submission
})

# Save to a CSV file
submission_df.to_csv('submission.csv', index=False)

print("Submission file created successfully: submission.csv")

Submission file created successfully: submission.csv